### PR TITLE
Fixed #10 - Updated references to NuGet packages to support CI server

### LINKED ISSUE #10: Add CI build
Add CI build, i.e. using AppVeyor (or something else).

This will also allow pull requests to be automatically verified, etc.

### PR DESCRIPTION
**Pull request by adilmughal**
Resolved issue #10 - Updated all VS extension sdk references as NuGet packages and appveyor.yml file to configure CI settings.

At this stage the appveyor.yml is configured to build only respective branch i.e. "AppVeyorConfig". Once reviewed and merged to master, please remove specific branch from appveyor.yml file. 

Also updated appveyor.yml to point for forked repository of scriptExtensions which supports multiple pushing multiple visx artifacts instead of one. Please note that I have commented publishing to gallery from appveyor.yml which can be configured when required.

### CODE REVIEW

**Comment by olegtk** [comment]
Awesome! Thanks, @adilmughal! :+1: 
Let me just validate this doesn't break our internal official build...

**Comment by olegtk** [comment]
Still working on it. Out internal official PPT build (which mirrors this repo and also contains not yet open sourced extensions) is running in an environment that doesn't support Nuget. So accepting this PR right now would break nightly official PPT build. I'm working on upgrading internal build to a more modern build environment with Nuget support.

**Comment by adilmughal** [comment]
How did you go @olegtk ? Would the internal system also have some kind of test automation so we know that after referencing NuGet packages we haven't break anything.

**Comment by olegtk** [comment]
Sorry, still struggling with that. Should be done by Monday.

**Comment by adilmughal** [comment]
@olegtk How did you go on this?

**Comment by G3Kappa** [comment]
@olegtk How did you go on this?

**Comment by olegtk** [comment]
Oh, we never took it? Sorry about that. Done.

**Pull request merged**
